### ISSUE TITLE
Add open graph support for sharing posts/qards

### ISSUE THREAD

**Issue by bhrose** [QardsJs/qards#18]
Enhancement/feature request: Posts like "[Welcome to Qards](https://www.qards.io/posts/welcome-to-qards-blogging-platform-for-professionals/)" are unable to render [card previews](https://cards-dev.twitter.com/validator) on Twitter because there's no card data found.

**Comment by ciokan** [comment]
That's the first issue I ever created: #1  :)

**Comment by bhrose** [comment]
Thanks @ciokan, really looking forward to your alpha release!
