### ISSUE TITLE
CJK character support

### ISSUE THREAD

**Issue by fr0der1c** [QardsJs/qards#76]
I've created a post with no Latin characters and the filename in git becomes `static/content/collections/posts/.md`. I assume if I have two posts with JCK characters would cause more trouble?

**Comment by ciokan** [comment]
Yeah, definitely! I haven't looked into that yet.

**Comment by fr0der1c** [comment]
I started using Qards for my technical blog. It's so beautiful that I cannot resist.

I can manually solve the filename problem. But later I found a more serious problem: If a widget contains CJK characters, it cannot be rendered. That's a big problem.

I'm not familiar with front-end so sadly I can't find the problem and fix it myself. I'm wondering if this problem would be fixed in the near future.

**Comment by ciokan** [comment]
Yes. Multi language support is a must as far as I'm concerned so I'll def. have that fixed.

**Comment by ciokan** [comment]
Please help me understand your issue better by telling me how to reproduce this issue as I want start working on it.

**Comment by ciokan** [comment]
Possible fix: https://github.com/QardsJs/qards/commit/130cf8f2e52e44e24239555326ef98e8049f9cf6
Please merge and confirm that your widgets are working with CJK chars

**Comment by fr0der1c** [comment]
The widgets are working with CJK characters now. Many thanks. 
However, the auto-generated URL (or filename) cannot work with CJK chars. For example, if I create a post in netlify CMS with CJK title, this will result in an article with URL: https://example.com/admin/#/collections/posts/entries/ . And this is a Not Found page.

![image](https://user-images.githubusercontent.com/16500161/50510183-ab477c00-0ac3-11e9-9997-feace2166c76.png)

To avoid this problem, I think users should be able to adjust the filename of the markdown file(also the URL) when editing posts.

**Comment by ciokan** [comment]
I switched the slug constraints from ascii to unicode with: https://github.com/QardsJs/qards/commit/59f1fc2caab034885fdd5d9c4b135dd5142db815

**Comment by fr0der1c** [comment]
![image](https://user-images.githubusercontent.com/16500161/50516440-d5aa3100-0ae5-11e9-84e5-da43f9872c6e.png)
![image](https://user-images.githubusercontent.com/16500161/50516447-db077b80-0ae5-11e9-8ad0-e566f28b0cfc.png)

Seems the problem is not fixed yet.

**Comment by ciokan** [comment]
Ok I'll dig deeper. I hope it's not something that has to be fixed upstream with Netlify cms.

**Comment by fr0der1c** [comment]
Thanks. Another related problem is that the "read time" count seems to ignore CJK chars. If a post is written in CJK, the number becomes completely useless.

![image](https://user-images.githubusercontent.com/16500161/50517306-d1344700-0aea-11e9-8885-9d3ee0cbffee.png)

**Comment by ciokan** [comment]
https://github.com/QardsJs/website/tree/master/static/content/collections/posts

I managed to submit such a post and it went through allright. Please make sure you clean the browser cache before refreshing the admin as some of the components might get cached. It's also worth waiting 5 mins after a netlify deploy to make sure the CDN will catch up and refresh the files.

I will try to address the read time as well.

**Comment by fr0der1c** [comment]
okay. I cleared cache and it's working as intended. However, I still suggest allowing users to edit URL.

**Comment by ciokan** [comment]
In the meantime you can edit the file name directly on disk to alter the desired slug.
