### ISSUE TITLE
Categories not found

### ISSUE THREAD

**Issue by fr0der1c** [QardsJs/qards#77]
I have three categories in my blog. After each build, only 1 of 3 would be available. Other two becomes not found page.

**Comment by fr0der1c** [comment]
I believe cloning my `blog` repo and build would reprod the problem.

**Comment by fr0der1c** [comment]
Any update on Not Found problem? Now I have three categories in the menu and only one of them rendered correctly, the other two says Not Found.

**Comment by ciokan** [comment]
Fixed by https://github.com/QardsJs/qards/commit/9f76d3f08614c9c9d41de6b0ad32cffdb45c8630
Please confirm

**Comment by fr0der1c** [comment]
Yes it's fixed.
