### ISSUE TITLE
Is there no landing page at all?

### ISSUE THREAD

**Issue by fr0der1c** [QardsJs/qards#78]
The official website qards.io does have a landing page. However, my blog is just a Not Found page. I tried to figure out if there is any way to get a landing page but I failed. So I come to ask if currently there is no landing page at all and not-found is the expected behaviour. If this is by design, a not-found page as a default landing page is just too...unfriendly, you know. 

I understand this project is in early development and something may not be functional, so I have to come here and ask. Sorry for the trouble.

**Comment by ciokan** [comment]
No trouble at all. There is a landing page in `app`. You just have to rename it. https://github.com/QardsJs/qards/tree/master/src/app/pages

**Comment by fr0der1c** [comment]
Thanks. It's working now.
