### ISSUE TITLE
Highlight disabled in TOC

### ISSUE THREAD

**Issue by fr0der1c** [QardsJs/qards#81]
In the earlier version, heading of the current paragraph is highlighted in Table of Contents. This behaviour disappeared in the latest version. Is this by design?

**Comment by ciokan** [comment]
No it's not. It's probably something that propagated down with these
changes in supporting non-latin chars.

**Comment by ciokan** [comment]
It will highlight now with the `secondaryAccent` background color: https://github.com/QardsJs/qards/commit/0569c52cbaebc03d17979e90e1ae6e596239a97a

**Comment by fr0der1c** [comment]
In some cases, all of the items in TOC are highlighted.

![image](https://user-images.githubusercontent.com/16500161/50532233-797cf680-0b51-11e9-92be-5609fec75ede.png)

https://blog.admirable.pro/sentry-sdk-cause-segmentation-fault/

**Comment by ciokan** [comment]
oh...goct it. Still non-latin issues. More fixes comming today. Thank you for bearing with me so far :)

**Comment by fr0der1c** [comment]
Another thing, which I'm not sure if it's related to non-latin, is that `Reference` card is not working on my site. Should I use the title of the post or the filename of the post in Reference card?
